name: "🐛 Bug report"
description: Report errors or unexpected behavior
labels: 
- bug
- needs-triage
body:
- type: markdown
  attributes:
    value: |
      Please make sure to [search for existing issues](https://github.com/heliomarpm/udemy-downloader-gui/issues) before filing a new one!
- type: input
  attributes:
    label: Udeler | Udemy Course Downloader 
    placeholder: |
      1.11.2
    description: |
      Check the version informed in the window title
  validations:
    required: true

- type: checkboxes
  attributes:
    label: Running as Business Account
    description: Are you running Udemy Business Account?
    options:
      - label: "Yes"

# - type: dropdown
#   attributes:
#     label: Area(s) with issue?
#     description: What things had an issue?  Check all that apply.
#     multiple: true
#     options:
#       - General
#       - Always on Top
#       - Awake
#       - ColorPicker
#       - Developer file preview
#       - FancyZones
#       - FancyZones Editor 
#       - Image Resizer
#       - Keyboard Manager
#       - MD Preview
#       - Mouse Utilities
#       - PDF Preview
#       - PDF Thumbnail
#       - G-code Preview
#       - G-code Thumbnail
#       - PowerRename
#       - PowerToys Run
#       - Shortcut Guide
#       - STL Thumbnail
#       - SVG Preview
#       - SVG Thumbnail
#       - Settings
#       - Video Conference Mute
#       - Welcome / PowerToys Tour window
#       - System tray interaction
#       - Installer
#   validations:
#     required: true

- type: textarea
  attributes:
    label: Steps to reproduce
    description: We highly suggest including a screenshots and a bug report log.
    placeholder: Tell us the steps required to trigger your bug.
  validations:
    required: true

- type: textarea
  attributes:
    label: ✔️ Expected Behavior
    placeholder: What were you expecting?
  validations:
    required: true

- type: textarea
  attributes:
    label: ❌ Actual Behavior / Steps to Reproduce 
    description: What happened instead, steps to reproduce the behavior?
    placeholder: |
      1. Go to ...
      2. Click on ...
      3. ...
    
  validations:
    required: true

